// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {memcached} from '../models';
import {service} from '../models';

export function Connect(arg1:string):Promise<void>;

export function DeleteContext(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetClient():Promise<memcached.Client>;

export function IsConnected():Promise<boolean>;

export function LoadContexts():Promise<Array<service.Context>>;

export function SaveContext(arg1:service.Context):Promise<service.Context>;
