// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['service']['ConnectionService']['Connect'](arg1);
}

export function DeleteContext(arg1) {
  return window['go']['service']['ConnectionService']['DeleteContext'](arg1);
}

export function Disconnect() {
  return window['go']['service']['ConnectionService']['Disconnect']();
}

export function GetClient() {
  return window['go']['service']['ConnectionService']['GetClient']();
}

export function IsConnected() {
  return window['go']['service']['ConnectionService']['IsConnected']();
}

export function LoadContexts() {
  return window['go']['service']['ConnectionService']['LoadContexts']();
}

export function SaveContext(arg1) {
  return window['go']['service']['ConnectionService']['SaveContext'](arg1);
}
