// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decr(arg1, arg2) {
  return window['go']['service']['OperationService']['Decr'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['service']['OperationService']['Delete'](arg1);
}

export function FlushAll() {
  return window['go']['service']['OperationService']['FlushAll']();
}

export function Get(arg1) {
  return window['go']['service']['OperationService']['Get'](arg1);
}

export function Incr(arg1, arg2) {
  return window['go']['service']['OperationService']['Incr'](arg1, arg2);
}

export function Set(arg1, arg2, arg3, arg4) {
  return window['go']['service']['OperationService']['Set'](arg1, arg2, arg3, arg4);
}

export function Stats() {
  return window['go']['service']['OperationService']['Stats']();
}

export function Version() {
  return window['go']['service']['OperationService']['Version']();
}
