// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function Decr(arg1:string,arg2:number):Promise<service.OperationResult>;

export function Delete(arg1:string):Promise<void>;

export function FlushAll():Promise<void>;

export function Get(arg1:string):Promise<service.OperationResult>;

export function Incr(arg1:string,arg2:number):Promise<service.OperationResult>;

export function Set(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function Stats():Promise<service.OperationResult>;

export function Version():Promise<string>;
